### PR TITLE
Fix build promise for helm and operator

### LINKED ISSUE #28: bug: kratix build promise does not work with helm-promise and operator-promise
### Description

Promise initialized with `kratix init helm-promise` and `kratix init operator-promise` defines a resource configure pipeline that's written to `workflows/resource/configure/workflow.yaml`

and looks like
```
- apiVersion: platform.kratix.io/v1alpha1
  kind: Pipeline
  metadata:
    name: instance-configure
  spec:
    containers:
    - env:
...
      image: ghcr.io/syntasso/kratix-cli/from-api-to-operator:v0.1.0
      name: from-api-to-operator
```
or 
```
- apiVersion: platform.kratix.io/v1alpha1
  kind: Pipeline
  metadata:
    name: instance-configure
  spec:
...
      image: ghcr.io/syntasso/kratix-cli/helm-resource-configure:v0.1.0
      name: instance-configure
```

When building promise with `kratix build promise` this generated workflow is not included in the final promise.

### Issue
`kratix build promise` is expecting the workflow.yaml file in a specific structure.
`kratix add container` generated workflow file looks like
```
promise: {}
resource:
  configure:
  - apiVersion: platform.kratix.io/v1alpha1
    kind: Pipeline
    metadata:
      name: instance-configure
    spec:
      containers:
      - image: test:latest
        name: test
```

### PR DESCRIPTION
**Pull request by richcooper95**
This PR fixes the `build promise` command for `init operator-promise` and `init helm-promise`.

The structure of `workflow.yaml` was an array of Pipelines for those commands, but `build promise` expected all of the workflows to be present.

The `build promise` and `add container` code has been changed to read/write an array of Pipelines so that all of the commands are consistent.

fixes #28

### CODE REVIEW

File: cmd/add_container.go [hunk 1]
```diff
@@ -211,41 +210,35 @@ func generateContainerName(image string) string {
...
-	switch workflow {
+	switch lifecycle {
 	case "promise":
 		switch action {
 		case "configure":
 			pipelines = allPipelines[v1alpha1.WorkflowTypePromise][v1alpha1.WorkflowActionConfigure]
 		case "delete":
 			pipelines = allPipelines[v1alpha1.WorkflowTypePromise][v1alpha1.WorkflowActionDelete]
-		default:
-			return nil, -1, fmt.Errorf("invalid action: %s", action)
```
Comment (richcooper95) [inline cmd/add_container.go:224]: This error handling is now handled in `generateWorkflow`

File: cmd/add_container.go [hunk 2]
```diff
@@ -211,41 +210,35 @@ func generateContainerName(image string) string {
...
 		switch action {
 		case "configure":
 			pipelines = allPipelines[v1alpha1.WorkflowTypeResource][v1alpha1.WorkflowActionConfigure]
 		case "delete":
 			pipelines = allPipelines[v1alpha1.WorkflowTypeResource][v1alpha1.WorkflowActionDelete]
-		default:
-			return nil, -1, fmt.Errorf("invalid action: %s", action)
 		}
-	default:
-		return nil, -1, fmt.Errorf("invalid workflow: %s", workflow)
```
Comment (richcooper95) [inline cmd/add_container.go:236]: This error handling is now handled in `generateWorkflow`

File: cmd/add_container.go [hunk 3]
```diff
@@ -38,8 +38,6 @@ var addContainerCmd = &cobra.Command{
 var (
 	image, containerName string
 	container            v1alpha1.Container
-	pipelineIndex        = -1
-	workflowTrigger      v1alpha1.Workflows
```
Comment (ChunyiLyu) [inline cmd/add_container.go:42]: nice!

File: cmd/add_container.go [hunk 4]
```diff
@@ -62,22 +60,24 @@ func AddContainer(cmd *cobra.Command, args []string) error {
...
 	fmt.Println("Don't forget to build and push your image!")
 	return nil
 }
 
-func generateWorkflow(workflow, action, pipelineName, containerName, image string, overwrite bool) error {
-	if workflow != "promise" && workflow != "resource" {
-		return fmt.Errorf("invalid lifecycle: %s, expected one of: promise, resource", workflow)
+func generateWorkflow(lifecycle, action, pipelineName, containerName, image string, overwrite bool) error {
+	var err error
+
```
Comment (ChunyiLyu) [inline cmd/add_container.go:78]: nitpick: 2 empty lines

File: cmd/add_container.go [hunk 5]
```diff
@@ -211,41 +210,35 @@ func generateContainerName(image string) string {
 	return strings.Split(nameAndVersion, ":")[0]
 }
 
-func findPipelinesForWorkflowAction(workflow, action, pipelineName string, allPipelines map[v1alpha1.Type]map[v1alpha1.Action][]v1alpha1.Pipeline) ([]v1alpha1.Pipeline, int, error) {
+func findPipelinesForWorkflowAction(lifecycle, action, pipelineName string, allPipelines map[v1alpha1.Type]map[v1alpha1.Action][]v1alpha1.Pipeline) ([]v1alpha1.Pipeline, int, error) {
```
Comment (ChunyiLyu) [inline cmd/add_container.go:213]: since you've renamed workflow to lifecycle, would you like to update the function name here to `findPipelinesForLifecycleAction()`?

**Review by ChunyiLyu — COMMENTED** [review]
Because this PR should make helm and operator promise work with build promise, could we add some test to `build_test.go` to build from `kratix init helm-promise` and `kratix init operator-promise`?

File: cmd/add_container.go (hunk 5 above)
Comment (richcooper95) [reply cmd/add_container.go:213]: I would! 👍

**Review by aclevername — APPROVED** [review]
